site_name: Base Hube
site_url: https://dezpyer.github.io/base-hub/
site_description: >-
  My little base sheet

# Repository
repo_name: zensical/zensical
repo_url: https://github.com/Dezpyer/base-hub
edit_uri: https://github.com/Dezpyer/base-hub/docs/edit/main/docs/

# Copyright
copyright: "Lana spend 1.9"

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Plugins
plugins:
  - search
  - tags

markdown_extensions:
  - zensical.extensions.glightbox

nav:
  - Overview: index.md
  - Base Collection: bases.md